name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity: ^3.0.2
  country_code_picker: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  firebase_core: ^2.15.0
  firebase_core_platform_interface: ^4.8.0
  firebase_messaging: ^14.6.5
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^5.4.3+7
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.6.2
  flutter_widget_from_html_core: ^0.10.3
  freezed: ^2.0.3+1
  geocoding: ^2.0.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.5.2
  http: ^0.13.1
  image_picker: ^0.8.1
  path_provider: ^2.0.1
  phone_number: ^2.0.1
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.5
  shimmer_animation: ^2.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.2
  url_strategy: ^0.2.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logomart.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
